###
# Welcome to the new js2coffee 2.0, now
# rewritten to use the esprima parser.
# try it out!
###

class GraphicsController

  constructor: ->
    that = this
    @previousData = {}
    @currentData = {}

    that.poll()

    # setInterval (->
    #   that.poll()
    #   ), 5000

    setInterval (->
      $(window).trigger('tick')
      ), 500

  poll: =>
    pollUrl = 'http://localhost:27015/graphics.json'
    # @previousData = @currentData

    $.ajax pollUrl,
    timeout: 15000
    success: (data) =>
      if !data
        console.log("No data received")
        return
      @currentData = JSON.parse(data)
      console.log @currentData
      window[widget].update widget for widget in @currentData

      # window[widget].update(widget) for widget in @currentData when @currentData isnt 'settings'
      console.log("Data dump: " + JSON.stringify(@currentData))
      # $(window).trigger('onPollingEvent')
      return
    return


class AnimatedObject
  constructor: ->
    @properties = { visible: true, content: {} }
    @animationSpeed = 500
    # $(window).bind('onPollingEvent', @update)  
    $(window).bind('tick', @tick)
    
  update: (widget) =>
    console.log widget
    # Delegate changes to animation system
    if @properties.visible != widget.visible
      console.log("Visibility changed")

    console.log("Update called on " + self)

    # console.log(controller.currentData.clock.visible)
    # console.log("Current data received: " + controller.currentData.test)
    # for property in @properties
    #   console.log(property)
      # console.log(controller.currentData[self.constructor.name])
  
  tick: ->
    


class Clock extends AnimatedObject
  tick: ->
    d = new Date()
    currentMinutes = d.getMinutes()
    currentSeconds = d.getSeconds()
    if currentMinutes.toString().length == 1
      currentMinutes = "0" + currentMinutes
    if currentSeconds.toString().length == 1
      currentSeconds = "0" + currentSeconds
    $('#clock').html(d.getHours() + ':' + currentMinutes + ':' + currentSeconds)

  hide: ->
    $('#clock').fadeOut()

  show: ->
    $('#clock').fadeIn()

controller = new GraphicsController();
clock = new Clock();

# ---
# generated by js2coffee 2.1.0